### ISSUE TITLE
Quiet beep has appeared at the end of some tunes!

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#181] opened 2018-03-25 15:55 UTC
In attract mode there is a quiet "beep" at the end of the title tune and the end of the first tune in the story cutscene when the Princess is looking out of the window.

Have heard it in other tunes throughout the game when play testing.  Thought this was real HW only but happens in b-em.

**Comment by inversephase** [comment] 2018-03-25 17:47
yeah, I hear it at the end of story2 as well, using jsbeeb

**Comment by inversephase** [comment] 2018-03-28 08:13
ok, in the current build, so far the only thing I hear it in is the end of story2. I'm pretty sure I uploaded a new story2 but I'll upload another one that will not confuse vgmconvert. that should fix the beep.

**Comment by simondotm** [comment] 2018-03-28 11:32
related to #184

**Comment by inversephase** [comment] 2018-03-28 12:38
if anyone can come up with more sources of beeps, absolutely please reply to #184

**Comment by simondotm** [comment] 2018-03-28 23:14
Closing this one, the problem is caused by the same thing

**Closed by simondotm** 2018-03-28 23:14 UTC
Labels: audio, bug
